🚑Fix : 깃헙 액션 워크 플로우 수정

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -75,62 +75,67 @@ jobs:
         run: |
           public_ip=${{ secrets.EC2_PUBLIC_IP }}
           echo "Public IP: $public_ip"
-          ssh -o StrictHostKeyChecking=no -i private_key.pem -T ubuntu@$public_ip <<'EOF'
-if ! command -v docker &> /dev/null
-then
-  echo "Docker not found, installing..."
-  sudo apt-get update
-  sudo apt-get install -y docker.io
-  sudo systemctl start docker
-  sudo systemctl enable docker
-fi
+          ssh -o StrictHostKeyChecking=no -i private_key.pem -T ubuntu@$public_ip << 'EOF'
+            if ! command -v docker &> /dev/null
+            then
+              echo "Docker not found, installing..."
+              sudo apt-get update
+              sudo apt-get install -y docker.io
+              sudo systemctl start docker
+              sudo systemctl enable docker
+            fi
 
-if ! command -v docker-compose &> /dev/null
-then
-  echo "Docker Compose not found, installing..."
-  sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
-  sudo chmod +x /usr/local/bin/docker-compose
-fi
+            if ! command -v docker-compose &> /dev/null
+            then
+              echo "Docker Compose not found, installing..."
+              sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
+              sudo chmod +x /usr/local/bin/docker-compose
+            fi
 
-sudo usermod -aG docker $USER
-newgrp docker
-echo "${DOCKER_HUB_PASSWORD}" | docker login --username "${DOCKER_HUB_USERNAME}" --password-stdin
-sudo systemctl restart docker
+            sudo usermod -aG docker $USER
+            newgrp docker
+            echo "${DOCKER_HUB_PASSWORD}" | docker login --username "${DOCKER_HUB_USERNAME}" --password-stdin
+            sudo systemctl restart docker
 
-# 기존 컨테이너 중지 및 제거
-if [ $(docker ps -a -q -f name=nest-backend) ]; then
-  docker stop nest-backend
-  docker rm nest-backend
-fi
+            # 기존 컨테이너 중지 및 제거
+            if [ $(docker ps -a -q -f name=nest-backend) ]; then
+              docker stop nest-backend
+              docker rm nest-backend
+            fi
 
-# 프로젝트 디렉토리 생성 및 이동
-mkdir -p /home/ubuntu/project
-cd /home/ubuntu/project
+            # 프로젝트 디렉토리 생성 및 이동
+            mkdir -p /home/ubuntu/project
+            cd /home/ubuntu/project
 
-# Docker 이미지 풀
-docker pull hotchapa/burger-nest:latest
+            # GitHub Actions 워크플로우에서 복제한 코드를 사용하여 프로젝트 디렉토리에 복사
+            docker pull hotchapa/burger-nest:latest
+            
+            # .env 파일을 EC2 인스턴스로 전송
+            echo "${{ secrets.DOTENV_FILE_CONTENT }}" > .env
 
-# .env 파일 생성
-cat <<EOT > .env
-MYSQL_ROOT_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD }}
-MYSQL_DATABASE=${{ secrets.MYSQL_DATABASE }}
-MYSQL_USER=${{ secrets.MYSQL_USER }}
-MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }}
-DB_HOST=db
-DB_PORT=3306
-DB_USERNAME=${{ secrets.MYSQL_USER }}
-DB_PASSWORD=${{ secrets.MYSQL_PASSWORD }}
-DB_DATABASE=${{ secrets.MYSQL_DATABASE }}
-EOT
+            # Docker Compose 파일 추출
+            docker run --rm -v $(pwd):/extract hotchapa/burger-nest:latest cp /usr/src/app/docker-compose.yml /extract
 
-# Docker Compose 파일 추출
-docker run --rm -v $(pwd):/extract hotchapa/burger-nest:latest cp /usr/src/app/docker-compose.yml /extract
+            # .env 파일 생성
+            cat <<EOT > .env
+            MYSQL_ROOT_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD }}
+            MYSQL_DATABASE=${{ secrets.MYSQL_DATABASE }}
+            MYSQL_USER=${{ secrets.MYSQL_USER }}
+            MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }}
+            DB_HOST=db
+            DB_PORT=3306
+            DB_USERNAME=${{ secrets.DB_USERNAME }}
+            DB_PASSWORD=${{ secrets.DB_PASSWORD }}
+            DB_DATABASE=${{ secrets.DB_DATABASE }}
+            EOT
+            
+            # Docker Compose 실행
+            docker-compose -f docker-compose.yml up -d
+            
+            # docker run -d --name nest-backend -p 3000:3000 hotchapa/burger-nest:latest
 
-# Docker Compose 실행
-docker-compose -f docker-compose.yml up -d
-
-docker image prune -f
-EOF
+            docker image prune -f
+          EOF
         env:
           DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
           DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
